name: CI/CD with Docker Hub and Versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract short Git commit SHA
      - name: Get short SHA
        id: vars
        run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # Step 4: Build and push Docker image with tags
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/online-ide:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/online-ide:${{ env.SHA_SHORT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 5: SSH into server and deploy
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/online-ide:latest
            docker stop online-ide || true
            docker rm online-ide || true
            docker run -d -p 5000:5000 --name online-ide ${{ secrets.DOCKERHUB_USERNAME }}/online-ide:latest
